import { StandardButton , Button} from "std-widgets.slint";

export component MainWindow inherits Window {
    icon: @image-url("icon/icon.png");
    title: "Calculator";
    min-width: 270px;
    min-height: 480px;
    preferred-width: 324px;
    preferred-height: 480px;

    in-out property <string> expression;
    callback request-modify-expression();

    VerticalLayout {
        spacing: 8px;
        padding: 8px;
        HorizontalLayout {
            Rectangle {height: output.height; background: #FF8D8B; border-radius: 5px;
                output := Text {
                    x: parent.x + 8px;
                    width: parent.width - 16px;
                    min-height: 48px;
                    wrap: word-wrap;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    font-size: 24px;
                    text: root.expression;
                }
            }
        }
        HorizontalLayout {
            spacing: 8px;
            Button {text: "<"; clicked => {root.request-modify-expression()}}
            Button {text: "C"; clicked => {root.expression = ""}}
        }
        HorizontalLayout {
            spacing: 8px;
            Button {text: "("; clicked => {root.expression = root.expression + self.text}}
            Button {text: ")"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "^"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "/"; clicked => {root.expression = root.expression + self.text}}
        }
        HorizontalLayout {
            spacing: 8px;
            Button {text: "7"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "8"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "9"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "*"; clicked => {root.expression = root.expression + self.text}}
        }
        HorizontalLayout {
            spacing: 8px;
            Button {text: "4"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "5"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "6"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "-"; clicked => {root.expression = root.expression + self.text}}
        }
        HorizontalLayout {
            spacing: 8px;
            Button {text: "1"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "2"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "3"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "+"; clicked => {root.expression = root.expression + self.text}}
        }
        HorizontalLayout {
            spacing: 8px;
            Button {text: "0"; clicked => {root.expression = root.expression + self.text}}
            Button {text: "."; clicked => {root.expression = root.expression + self.text}}
            Button {text: "(-)"; clicked => {root.expression = root.expression + "-"}}
            Button {text: "=";}
        }
    }
}
